# Generated by Django 4.0 on 2022-01-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11, verbose_name='cuit')),
                ('razon_social', models.CharField(max_length=100, verbose_name='razon social')),
                ('nombre_fantasia', models.CharField(max_length=100, verbose_name='nombre de fantasia')),
                ('fecha_inscriocion', models.DateField(verbose_name='fecha de inscripcion')),
                ('direccion_fiscal', models.CharField(max_length=100, verbose_name='direccion fiscal')),
                ('direccion_envio', models.CharField(max_length=100, verbose_name='direccion envio')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('emai', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('provincia', models.CharField(max_length=50, verbose_name='provincia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('codigo_postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empelado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=11, verbose_name='cuil')),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('domicilio', models.CharField(max_length=100, verbose_name='domicilio')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('celular', models.CharField(max_length=20, verbose_name='celular')),
                ('cargo', models.CharField(max_length=50, verbose_name='cargo')),
                ('email', models.EmailField(max_length=254)),
                ('companiaId', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
