# Generated by Django 4.0 on 2022-01-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionaria',
            name='fecha_inscriocion',
            field=models.DateField(verbose_name='01/01/1990'),
        ),
        migrations.AlterField(
            model_name='empelado',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='01/01/1990'),
        ),
    ]
