# Generated by Django 4.0 on 2022-01-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCompany', '0002_alter_concesionaria_fecha_inscriocion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concesionaria',
            old_name='fecha_inscriocion',
            new_name='fecha_inscripcion',
        ),
    ]
